### ISSUE TITLE
ffmpeg module re-addition

### ISSUE THREAD

**Issue by jsauer-NCAR** [NCAR/spack-casper#1]
Seems perhaps the ffmpeg module was discontinued in the upgrade to the new OS stack.  May I please request it be added and kept up-to-date in the new OS stack?  It is a very useful utility for creating animations from high-density image sequences.

**Comment by vanderwb** [comment]
Hey Jeremy - `ffmpeg` is still available on Casper. In the production stack, we've decided to make it available in the default environment. No specific module load is required (aside from the top-level `ncarenv` module).

```
[22:27] ~$ ml

Currently Loaded Modules:
  1) ncarenv/23.10 (S)   2) intel/2023.2.1   3) ncarcompilers/1.0.0   4) cuda/12.2.1   5) ucx/1.14.1   6) openmpi/4.1.6   7) hdf5/1.12.2   8) netcdf/4.9.2

  Where:
   S:  Module is Sticky, requires --force to unload or purge


[22:28] ~$ ffmpeg -version
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 7 (SUSE Linux)
...
```

**Comment by jsauer-NCAR** [comment]
Indeed, I see it now, my apologies for the erroneous request.  Thank you!

**Comment by vanderwb** [comment]
Not a problem. It's good to know what folks find valuable. :)
